
name: Build
on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-14]
    runs-on: ${{ matrix.os }}
    env:
      DAWN_VERSION: chromium/6997
    defaults:
      run:
        shell: ${{ matrix.os == 'windows-latest' && 'msys2 {0}' || 'bash' }}

    steps:
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.4

    - name: Get CMake
      uses: lukka/get-cmake@latest

    - name: Clone Dawn
      run: git clone --depth 1 https://dawn.googlesource.com/dawn -b ${{ env.DAWN_VERSION }}

    - name: Install deps on Linux
      if: matrix.os == 'ubuntu-20.04'
      run: |
        sudo apt-get update 
        sudo apt-get install -y mesa-utils mesa-vulkan-drivers
      
    - name: Setup MSYS2
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64

    - name: Configure build
      env:
        SCCACHE_GHA_ENABLED: "true"
      run: |
        cmake -B build -G Ninja -S dawn \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
        -DCMAKE_C_COMPILER_LAUNCHER=sccache \
        -DDAWN_USE_GLFW=OFF \
        -DDAWN_USE_X11=OFF \
        -DDAWN_USE_WAYLAND=OFF \
        -DDAWN_ENABLE_D3D11=OFF \
        -DDAWN_ENABLE_D3D12=OFF \
        -DDAWN_ENABLE_EMSCRIPTEN=OFF \
        -DDAWN_ENABLE_NULL=OFF \
        -DDAWN_ENABLE_DESKTOP_GL=OFF \
        -DDAWN_ENABLE_OPENGLES=OFF \
        -DTINT_BUILD_SPV_READER=OFF \
        -DDAWN_BUILD_SAMPLES=OFF \
        -DTINT_BUILD_CMD_TOOLS=OFF \
        -DTINT_BUILD_TESTS=OFF \
        -DTINT_BUILD_IR_BINARY=OFF \
        -DDAWN_FETCH_DEPENDENCIES=ON \
        -DDAWN_ENABLE_INSTALL=ON \
        $([[ "${{ matrix.os }}" == "windows-latest" ]] && echo "-DDAWN_ENABLE_VULKAN=ON") \
        $([[ "${{ matrix.os }}" == "macos-14" ]] && echo "-DCMAKE_OSX_ARCHITECTURES='arm64;x86_64'")
      

    - name: Build
      run: cmake --build build

    - name: Install
      run: cmake --install build --prefix install

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webgpu-dawn-chromium-6997-${{ matrix.os }}
        path: install